### ISSUE TITLE
ERR error="failed to purchase item with param 'STDQ': failed to purchase app" success=false

### ISSUE THREAD

**Issue by SlideShowGames** [majd/ipatool#297] opened 2024-10-14 02:31 UTC
### What happened?

I did the ipa purchase command and I got this error, this happens with every app.

### Version

2.1.4

### Relevant log output

```shell
% ipatool purchase -b com.apple.AccessoryDevelopAsst
10:29PM ERR error="failed to purchase item with param 'STDQ': failed to purchase app" success=false
```

**Comment by r4ptus** [comment] 2024-10-16 14:50
got the same error

**Comment by sophiawisdom** [comment] 2024-10-16 17:22
#284

**Comment by majd** [comment] 2024-12-12 22:46
Duplicate of #284.

**Closed by majd** 2024-12-12 22:46 UTC
Labels: bug
