### ISSUE TITLE
Ipatool won't download app...?

### ISSUE THREAD

**Issue by cinematic6436** [majd/ipatool#286] opened 2024-07-20 22:59 UTC
### What happened?

Using ipatool-2.1.4-windows-amd64.exe, I try to download a free app using the following command --

ipatool purchase -b com.medicalappleidkm.miogymGame

I'm asked for my Apple password, the 2-factor code, and a passphrase (which I think is just my login password) and get the following error --

ERR error="failed to purchase item with param 'STDQ': failed to purchase app" success=false

In a previous post majd said, "This is the passphrase that you entered when using ipatool for the first time, it's used to encrypt the credentials when stored on your file-system on non-macOS platforms. If you forgot the passphrase, you can remove the .ipatool directory in your home folder and re-authenticate using ipatool auth login."

I deleted the .ipatool and re-authenticate, but I still can't download the ipa. I also tried it with another free app with the same result (com.google.ios.youtube). Any idea what's stopping me from downloading either ipa?

### Version

ipatool-2.1.4-windows-amd64.exe

**Comment by iteroji** [comment] 2024-08-23 08:08
this looks the same as https://github.com/majd/ipatool/issues/284#issue-2420325147

**Comment by majd** [comment] 2024-09-23 20:51
Duplicate of #284

**Closed by majd** 2024-09-23 20:51 UTC
Labels: bug
