### ISSUE TITLE
license is required?

### ISSUE THREAD

**Issue by bkmamba20** [majd/ipatool#199] opened 2023-06-05 10:54 UTC
### What happened?

when i try to download ipa file "ipatool download --bundle-identifier com.apple.TestFlight -output test.ipa"

ERR error="license is required" success=false

### Version

v2.1.2

### Relevant log output

```shell
ipatool download --bundle-identifier com.apple.TestFlight --output test.ipa
4:22PM INF enter passphrase to unlock "/root/.ipatool" (this is separate from your Apple ID password):
downloading   0% |                                                                                                                                                                                  | ( 0/ 1 B) 4:22PM ERR error="license is required" success=false
```

**Comment by majd** [comment] 2023-06-05 19:38
Duplicate of #184

**Closed by majd** 2023-06-05 19:38 UTC
Labels: bug

**Comment by sathiyapriyanofficial** [comment] 2025-08-13 08:20
# Resolving "License is Required" Error in ipatool

When using [`ipatool`](https://github.com/majd/ipatool), you might encounter the following error:

```
Error: license is required
```

This happens because `ipatool` requires a valid license linked to your Apple ID for any app you download — even free apps.

---

## Steps to Resolve

### 1. Search for the App
Make sure the app exists and is available for your account.

```
ipatool search --limit 1 app_name
```

> **Note:**  
> The app must have been "purchased" or downloaded at least once on your Apple ID.  
> If you don’t have an iPhone (only a Mac), proceed to Step 2.

---

### 2. Obtain a License (Using Purchase Command)
Use the `purchase` subcommand to get a license, even for free apps.

```
ipatool purchase --bundle-identifier com.ubercab.UberClient
```

---

### 3. Download the IPA with the `--purchase` Flag
Once the license is attached to your Apple ID, download the app:

```
ipatool download --bundle-identifier net.whatsapp.WhatsApp --output WhatsApp.ipa --purchase
```

---

## Why This Happens
`ipatool` interacts with the App Store to fetch `.ipa` files. The App Store requires a valid license before allowing the download — this applies to both **paid** and **free** apps.  
Running `purchase` ensures a license is registered to your Apple ID, making the download possible.

---

## Tips & Troubleshooting
- Always log in with a valid Apple ID in `ipatool` before running these commands.
- For multiple apps, repeat the **purchase** step for each bundle identifier.
- Example for multiple apps:
    ```
    ipatool purchase --bundle-identifier com.twitter.ios
    ipatool purchase --bundle-identifier com.facebook.Facebook
    ```
- If you still see the error, try logging out and back into `ipatool`:
    ```
    ipatool auth revoke
    ipatool auth login
    ```
```
