### ISSUE TITLE
ipatool purchase error

### ISSUE THREAD

**Issue by adrianzhang** [majd/ipatool#315] opened 2024-12-02 08:50 UTC
### What happened?

When login and search the app successfully, I'am continue to purchase app and then get error:

```
ipatool search perplexity
4:34PM INF apps=[{"bundleID":"ai.perplexity.app","id":1668000334,"name":"Perplexity - Ask Anything","price":0,"version":"2.34.1"},{"bundleID":"com.intelliapps.ai.chat.bot.macapp","id":6445991020,"name":"AI Chat Bot: Ask Open Question","price":0,"version":"1.6"},{"bundleID":"com.swamtech.chatgpt","id":1661075748,"name":"Ask AI Anything - Meta AI App","price":0,"version":"3.7"},{"bundleID":"com.microsoft.bing","id":345323231,"name":"Microsoft Bing Search","price":0,"version":"29.9.421128001"},{"bundleID":"com.codeway.chatapp","id":1668787639,"name":"Chat \u0026 Ask AI by Codeway","price":0,"version":"2.5.7"},{"bundleID":"co.vulcanlabs.moodtracker","id":1559479889,"name":"AI Chatbot: AI Chat Smith 4","price":0,"version":"7.6.0"}] count=6

ipatool purchase -b ai.perplexity.app
4:35PM ERR error="failed to purchase item with param 'STDQ': This Apple\u00a0Account is temporarily unable to be used in the iTunes Store because it could not be found. Try again later." success=false
```

I can login to AppStore on my Mac (MacOS 12.6.1 Monterey), but cannot purchase the app in it because it needs MacOS version 13.

I used to use ipatool to buy 2FAs app, that app also need higher iOS version than my iPhone and purchase was successful. So I don't think the error caused by old MacOS version or Apple device OS version.

### Version

ipatool -v ipatool version 2.1.4

**Comment by majd** [comment] 2024-12-12 22:46
Duplicate of #284.

**Closed by majd** 2024-12-12 22:46 UTC
Labels: bug
