### ISSUE TITLE
Big Sur 11.6.5: dyld: Library not loaded: @rpath/libswift_Concurrency.dylib

### ISSUE THREAD

**Issue by cpatulea** [majd/ipatool#69] opened 2022-04-20 03:48 UTC
### What happened?

Binary fails to start, see log.

### Version

1.1.0

### Relevant log output

```shell
$ brew tap majd/repo
...
==> Tapping majd/repo
Cloning into '/usr/local/Homebrew/Library/Taps/majd/homebrew-repo'...
remote: Enumerating objects: 50, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 50 (delta 14), reused 49 (delta 13), pack-reused 0
Receiving objects: 100% (50/50), 7.27 KiB | 2.42 MiB/s, done.
Resolving deltas: 100% (14/14), done.
Tapped 1 cask and 1 formula (16 files, 16.6KB).
~$ brew install ipatool
==> Downloading https://github.com/majd/ipatool/releases/download/v1.1.0/ipatool-v1.1.0.zip
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/369755856/60b
######################################################################## 100.0%
==> Installing Cask ipatool
==> Linking Binary 'ipatool' to '/usr/local/bin/ipatool'
🍺  ipatool was successfully installed!
~$ ipatool auth login
dyld: Library not loaded: @rpath/libswift_Concurrency.dylib
  Referenced from: /usr/local/bin/ipatool
  Reason: image not found
Abort trap: 6
```

**Comment by liorazi** [comment] 2022-04-20 12:42
Possible duplicate of [#50](https://github.com/majd/ipatool/issues/50).
Please see more instructions in the issue link.

**Closed** 2022-04-20 18:49 UTC
Labels: bug, duplicate
